# Generated by Django 3.2.11 on 2022-11-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='penalty',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
