# Generated by Django 3.2.11 on 2022-11-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogApp', '0003_auto_20221117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pwd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
